### ISSUE TITLE
Danger error when calculating the Git Diff size

### ISSUE THREAD

**Issue by iangmaia** [Automattic/dangermattic#68]
The error was seen on this PR: https://github.com/woocommerce/woocommerce-android/pull/11636
Internal reference: p1717157465536019-slack-C02KLTL3MKM

It was triggered when calling `pr_size_checker.check_diff_size`, where we access the Git data using `info_for_file` / Diff Git APIs.

```console
output: "fatal: Not a valid object name \n"
 #  from Dangerfile:37
 #  -------------------------------------------
 #  
 >  pr_size_checker.check_diff_size(
 #    max_size: 300,
 #  -------------------------------------------

lib/ruby/gems/3.2.0/gems/git-1.19.1/lib/git/lib.rb:232:in `object_type'
lib/ruby/gems/3.2.0/gems/git-1.19.1/lib/git/object.rb:301:in `new'
lib/ruby/gems/3.2.0/gems/git-1.19.1/lib/git/base/factory.rb:69:in `object'
lib/ruby/gems/3.2.0/gems/git-1.19.1/lib/git/diff.rb:94:in `blob'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb:146:in `info_for_file'
lib/ruby/gems/3.2.0/gems/danger-dangermattic-1.1.1/lib/dangermattic/plugins/pr_size_checker.rb:121:in `block in diff_size'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/helpers/array_subclass.rb:49:in `sum'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/helpers/array_subclass.rb:49:in `respond_to_method'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/helpers/array_subclass.rb:19:in `method_missing'
lib/ruby/gems/3.2.0/gems/danger-dangermattic-1.1.1/lib/dangermattic/plugins/pr_size_checker.rb:117:in `diff_size'
lib/ruby/gems/3.2.0/gems/danger-dangermattic-1.1.1/lib/dangermattic/plugins/pr_size_checker.rb:54:in `check_diff_size'
from Dangerfile:37:in `eval_file'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:311:in `eval'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:311:in `eval_file'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:204:in `block in parse'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:201:in `instance_eval'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:201:in `parse'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:287:in `run'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/danger_core/executor.rb:28:in `run'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/lib/danger/commands/runner.rb:73:in `run'
lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
lib/ruby/gems/3.2.0/gems/danger-9.4.3/bin/danger:5:in `<top (required)>'
bin/danger:25:in `load'
bin/danger:25:in `<main>'
```

**Comment by ParaskP7** [comment]
RTO: @iangmaia I am seeing the status on this issue as `Planned` on our roadmap, is that still the case? 🙏

**Comment by iangmaia** [comment]
I'll move it back to `Idea`. This needs thorough investigation and I haven't seen further reports, so maybe it was just a one off?
